[project]
name = "aiinthewildgp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "djitellopy>=2.5.0",
    "mediapipe>=0.10.21",
]
